apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.5.0/manifests/install.yaml
  - 01-argocd-route.yaml

patches:
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    patch: |
      - op: add
        path: /data
        value:
          server.insecure: "true"
  - target:
      kind: ConfigMap
      name: argocd-cm
    patch: |
      - op: add
        path: /data
        value:
          kustomize.buildOptions: "--enable-helm"
