apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newt

resources:
  - newt-sealedsecret.yaml

helmCharts:
  - name: newt
    repo: https://charts.fossorial.io
    version: 1.5.0
    releaseName: newt-tunnel
    namespace: newt
    valuesInline:
      newtInstances:
        - name: external-tunnel
          enabled: true
          auth:
            existingSecretName: "newt-auth"
          configPersistence:
            type: emptyDir
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          hostNetwork: true
          extraVolumes:
            - name: config-dir
              emptyDir: {}
          extraVolumeMounts:
            - name: config-dir
              mountPath: /.config
