# cluster/apps/homepage/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Tell Kustomize which raw files belong to this app
resources:
  - homepage.yaml
  - 01-homepage-route.yaml # Include ingress.yaml or configmap.yaml here too if you have them
