apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - newrelic-license-sealed.yaml  # Our encrypted secret file

helmCharts:
  - name: nri-bundle
    repo: https://helm-charts.newrelic.com
    version: 7.x.x # Locks down major version updates
    releaseName: newrelic
    namespace: newrelic
    valuesFile: values.yaml
