---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: newrelic-license-secret
  namespace: newrelic
spec:
  encryptedData:
    licenseKey: AgCaDiI8WNMA0KU0m+Wq99RKH/Sp6y7+FUFBNcy+OJW2j1DbNHJSt6xQUn3VntSHrUghGhqxYxKci48J6lWq3rgFP8zVnH3nfLVJg7KXAYcj4EB68/5+MxRsS0l/h6P9l+5YH4no30z9WVrQvvp0kCJzS98ZBfdM0JKghPYI41S0w1mF/Bjcsp49N1mHaIxGl0kg6mjomuRFc9LEwkKQaskeySxnF1m+nSQBPYGAMDervR7StfzVUd1QAa9ypq52dQFUtUu+teRCuOyu5v7ntinaqUt5tAGBdGX/5sCNZg+/HTCalZzHF1TBxDlqaYLskdQEsKChQLmuQJwNHrMpvzNclZ2ii/7LUyWdwcdqj8OXFbwxXd91umFyNNHCRgqPHD4GF5byvFNFfly8db47684PEUCfvQotF8+9BpX/iAcGKe2nXi2EaPSkAQQ3aH7GAgkyD+B6rRBZ88Jp/4anglT9OKQRwHe2AdE4PLe4uxjohd+Vj4y/E46YxZiWCj2Kjlb8VnQq9/uxthvtHjw5YKEXaQjom5AavKEnCz37XCkLB5NnsDUf9xmUOUrRw37wklg9rfZ8UbrswiIytAcRaKBkrOmhiKhQRN9/zBECo9tqdbul0BFq55q3xBxmc2t5p8K4z4E8HPywIiago1JoWLMleJYhO8asIYeFAVuyeOMILPeGhbuGwHHQGD2DTh5gYEz3NyKNipPr0MUYk7vSrKXbtAwCzC2q1OqNsK7NB6WXJ6K7PnqB//m/
  template:
    metadata:
      creationTimestamp: null
      name: newrelic-license-secret
      namespace: newrelic
