apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: default-replica-count
value: "1"

---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: allow-volume-creation-with-degraded-availability
value: "true"

---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: disable-revision-counter
value: "true"

---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: replica-soft-anti-affinity
value: "true"

---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: snapshot-max-count
value: "7"

