apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  adguard.override: |
    # This sits inside the main server block, overriding the default forwarder
    forward . adguard-home.kube-system.svc.cluster.local
