apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  adguard.server: |
    # Intercept all generic traffic before it hits /etc/resolv.conf
    # and route it over to the internal adguard service
    forward . adguard-home.kube-system.svc.cluster.local
