---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-claim-secret
  namespace: plex
spec:
  encryptedData:
    PLEX_CLAIM: AgAORBuEXDN9HsR+Gl7XAMVE3+q5BPh5bzaMllyAggoe8oktK6w5fV0Ioti2AIXv+5QXkB+NFZMF6beJEbiWGzbuLXUGn+iR3FtBYZju5X6/9tSIjghzTO2QhvRa3+aNnNij1jb8nXFil/dbqb1YC+rmNIOmotvBHM0Kz9EKSFjW8KxmadMD/4Rew/6BFb0KCH/VR0O8juFoFhWhXywA7HN/AXJtq5Q9+f7Nmy/fQ1pU3TD0OV873bch2Cgc/038aoxeyxHrA/GFGmrq3kDHfMfZR+U0wql7GRGT+5vd9o3SpyEyhw/xsYrxT21N4IZKeo36J4oY+CRFv2YMB8jH8TlyRLcL2oUSa3iHhuz1VBUHLaq+t1x8BjxfWzqZHWZrBFlHvldfIGXKJS6j8xvbhx19ZYxYoWbw+3PUm59Wg+04EjigNTzLp+CpZpSHiaCvN+qJ6Fz5/t3WZebXAZ/eBH1Pq4rnJDKelOrNcQCYuBwsS+01oeHVJ11hEOud7lqJEaje8C0Ea3iEJk/drko4chBqsTKuuC/EFYEJuFfq+0h+pb4FhLpqM+MQDlv+WUVSiInjR/qTQUigO/LVS/SeFQfwawwqGNeyIuDLNMLoRFwdqVcO09jtWhqvXY94XftxuI0nFNHwR00x5s1XJiPouwidm/gVg9Uambi1z1ruyayAHH/kgbOyseCTzi5EEwPR+eNyps8M+/RyWMJJLyxCkfrqzfGWVfBfBIAGqQ==
  template:
    metadata:
      creationTimestamp: null
      name: plex-claim-secret
      namespace: plex
