# cluster/apps/arrs/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproutes.yaml
  - nfs-volume.yaml
  - nfs-pv.yaml
  - radarr.yaml
  - sonarr.yaml
  - lidarr.yaml
  - bazarr.yaml
  - prowlarr.yaml

# THE VERSION REGISTRY FOR THIS DOMAIN
images:
  - name: lscr.io/linuxserver/radarr
    newTag: 6.3.0
  - name: lscr.io/linuxserver/sonarr
    newTag: 4.0.19
  - name: lscr.io/linuxserver/lidarr
    newTag: 3.1.0
  - name: lscr.io/linuxserver/bazarr
    newTag: 1.5.6
  - name: lscr.io/linuxserver/prowlarr
    newTag: 2.4.0

# AUTOMATICALLY INJECT COMMON ENVS TO ALL DEPLOYMENTS HERE
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "100"
          - name: TZ
            value: "Australia/Sydney"

