# cluster/apps/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Register the homepage folder as a resource managed by this master list
resources:
  - ./homepage

# THE MASTER VERSION REGISTRY
images:
  - name: ghcr.io/gethomepage/homepage
    newTag: v1.13.2 # ◄── Put the version you want running here

# Global policy injection
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/revisionHistoryLimit
        value: 5
  - target:
      kind: StatefulSet
    patch: |-
      - op: add
        path: /spec/revisionHistoryLimit
        value: 5

# Change rolling updates to recreate 
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/strategy
        value:
          type: Recreate
