apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/x-dan-x/k3s.git'
        revision: HEAD
        directories:
          - path: cluster/apps/*
  template:
    metadata:
      name: 'app-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/x-dan-x/k3s.git'
        targetRevision: HEAD
        path: '{{path}}'
        kustomize:
          patches:
            - target:
                kind: Deployment
              patch: |-
                - op: replace
                  path: /spec/strategy
                  value:
                    type: Recreate
            - target:
                kind: Deployment
              patch: |-
                - op: replace
                  path: /spec/revisionHistoryLimit
                  value: 5
            - target:
                kind: StatefulSet
              patch: |-
                - op: replace
                  path: /spec/revisionHistoryLimit
                  value: 5
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
