---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-vpn-creds
  namespace: downloaders
spec:
  encryptedData:
    password: AgCDm4Q330fe38gReAavroY4qmcsXATfQ/sXGJhjwGG6sJlNvH/phF2L16blAJrd2fz+2+GdKgbo7n2W1FuLdNl8/Qx3prOQ6nExHs8HoWkS1FPPVfDI1o5661f6wx7kAMAsNMvX3V+CkjI0LKjWxtZO9kcgbNfep4gCWtayKV7w4BIFXClWHD0zji4fAZZYEH8t/0KHoaQR4OdWHARcjz/S6bZmSUhVF1ctllbNo37NYwMC/bVe+YfmGrNVpH5RPeDfYgc8VpMkIrP1Y7POBvF0+jnzcIVaxThEWvcsYls00HtDB5WBFiAT/LAYoMlBkIdKuNS/EHFOBo+eOd2GrOQQ1tMxZkHBarfD7tRaefTz9bODvyhe/W2Y6TJQbvB2blFkP10T2eFl67iOL1zrQ1LbISfVYJ4SRqKZc2CV4hL/KfOqjHY+ZR9zEf8DXmV1E+AjJ7LfD4j/JSqDjstjHvEGHv1kcPdD4wx1RSHxx71c8LW5v/Nl/+GuefqmFNdwhxME1ObOHpCV8yavceLM27QzEqRQC2/EF7Q3K9IVjFTA9jhGbzfAi/4TIVALIQ99sgE2gxMsx+N4l6f6JofrB7NkzQbNamepej3H6YgMbkI7qVKgcuHNlcslOr7vlh9lnnprG5g1EvUsZJME6XOtX4vRCbLV3oLWiIQkvmLXnIpZ64Ny3aNjc6U+XCpKjXyXPYthhUc236xAkY11
    username: AgAUuhGbK+A8dcL/XAAZG/G/yAaFhk6OMqf1nWHtJq34Ko69lLdjik3zhTTmgcbr7h8YzxClJHb3VE6p6UAc/82knvV8XPUJ7JZR41+qJZeTChzH8sYlr+k+XqoziGaJ2PsKRJrLkRNd6Yl2ReVlZt3P/yAak3sc345iQ/e5TOnNSHePjm3gEpaILUBYUt3vi2YQcAcfPSZym4GSd61dzET8D5oaTk0UyREVebM6p4vXzfr6zP/+IUT3cqYL6m1eQOaGiXjc8oWJSFDQfH79GYVKCay5D0htim5csp1gK7Ihr3jnkyg7FWUv6dv8FYIFlPTAz5gmarcpkMBA31+20n8CrM+O78LqckNcCagwf7Ko9BKt7UZL/6hvhuHQN2tc/iEo+jq6cOPiNbf9E842riIJs3Rqd1ePi2YSCArb2wEonlu1XOog3s5hlHfpb5MUBBYb5WNoMjVw9iSRdGwSFn/Z67xw8Kt+nYAsjfR9QspVMtMhfNUcRijZ5VoVFY4Ud1GguIYyXdNAVVki6WiD6y0ILTOAs/hTO0jFrVPP2W9kKlC0bRbHEqS0YwHmmmbEj5AHJ87c1+RZkc2Svj0MlPp607TP7mHd5kBhm7e+X0PODoJqQSTlL8VEQn+5KROJUcZT8b8hggOcQgHP5XamOxtK6K/BjkRq70LVYFuJkDIXrjG1hch0ZQhzpV2FmbkEDFq+gwJ9OK0pfg==
  template:
    metadata:
      creationTimestamp: null
      name: transmission-vpn-creds
      namespace: downloaders
