[k3s_cluster]
k3s-03 ansible_host=192.168.10.123 

[k3s_cluster:vars]
ansible_user=dan
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
