---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBCNvIzKtJvPisdNf3M0E9ZSL46+UIHc7HJ9BHNp2OBuENVyXGFpW/fnsm5Sm15PtHWtBzVbBz6wyD+8a63x2i4up+M9rBHFvjt5gZDWr9/ENMfJqlRDWeBQAu+anatslGfRo54Qw2XYA+3D+cSKu7RJ4SenIx75Sh5zmmKOyE2+5TiuEszJ1EKmC5nPLhbuqkm6hx15p+Tn+wMhTVEIUv8jQrDFnQbWvCwOj2wmtsmjZJ+jajdbAa8fJRyr+Jq5+OjVSuMmNlrDdz5l8XzGlJywFsdictX6VOaaz8/+ZolUms5CBd2wQO9xJdug/ALCKZl8UlRn7yv9EQ1plUH9zKsCqqs1MCVTRaKCxYaOXs9P+nKm6l18ng9bw0d6xMX5bjFlZinZT9c22fplo/2txKq+VeEoKwaolgWl89ogGG8h4/IVqPnQZE2hpyGYIUTQEfIF7yckCe7a34U3uHdmBisXMXogrK/WYxcJ68FX5n+VRZ2DqltRQ2rTURd0CidEdJtZCqFr3zEehCUHFayamjD9/psopTqMpOLprs75iDKuGoru0pGqYQIXKfNRcrz6PoDFmVje1lGGrB61Wj/apzmHv6tkiBcyhossw0ZP21TJq4eO1od9zNR3zzNhGnM2RLUx1976iEYsqt4rrNHgNo2/8Q2hn7XqL0yKrZMDRpRik2nYuJRiG7xZPJ0K78vQV/N+XHDg6fd2obg97VIlyPm+lKO25r/HC472x2AGnj8a2OzDWTPCagVRmsIysFnzKrq1H13Jw==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
