# cluster/apps/media/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nfs-volume.yaml
  - sabnzbd.yaml
  - transmission-vpn.yaml
  - transmission-sealedsecret.yaml
  - httproutes.yaml
