---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-vpn-creds
  namespace: media
spec:
  encryptedData:
    password: AgBgpW8yPrgba9BI9JxsQoaae0T7G46QlH1sT2+XJ9oTourLSK8hYr1WHut4Lu36gLNzVao4XJAsMHTyeowXTyzZMN3m4/Wi1qcwjnQXItuG5EJnXoKNkYlqMR7ujgN7golAClls+YeRTI6JRzEra0qnCm/m4WgBUvsp82k2sgEdCGRHB7lLiqj5vcBziAsRvbl0wX6w4qnZnTpjUTL33tPgBWhwkfm5F4KPueG0rwBOMKgBMkz9+cDXRrvQnE5ZWAyC0cdBRONE7wvucaJRQIm4KbD8N4jJmFUOua5+u10qpuqzp0hxPM3ux09yGD6YgtX4ErEaZCDScc+Hh2btV9VWo5TzxlVJM/dQRPkehi6ePEPJJHJlte+8QwNGJSDkTnEe7bf0+pdSPPJJS6rxdwUHPklAq4UzHjotwcmeDAFOSesA71DxR9yOZbbGRLnGPQ/BBZeEAH44gZQ6t6a8TLvVJvVu4w/AbVxx2zeZv9g6PYs+eixWMGolq5ygO17+4aHUxYWQlJSFqD9itrJLjQ88Zn5ql5yqKaYIaWRcgyMdfOFs2+WtrK0X8dSX9VqzE7bHqPHO58DJS3m3+sAMNv7AT5Nz2g8OTLecUacoN05rmCGrg+rTEoSMOX5JdMn3Qiw8cUzETEMxiwYHBZ6QFhlceGmXyArxZAy4Ind8EGNQ5EEy52/GnpxMHagfQH154n//rXh+Bp6JwEwW
    username: AgARBp1uBH9QHxBzH9gAGoGKHMWaP0n0myjyRURnCTyy0KrpjNUgvLaloY1AT/hpcaErlP67I5LI/MLLBc5MptPHUAk5PYwyJHJi865XZ29xP3CZKJVnUNRmbaNWXH0F1T3D92fpaViQhciYzQ7B+R0F21b78ml1RawQSUEovtX/mVWSXXFcp8K8rz+ztP1RDyOWvu/uslO/Ag3OA4vBX3qveiK/7p4yPeNfdvwoDeXPTJ3/UhRz6gghKdLZ5qlzNedK7RtU+XFR08oeLJ52/4peOD8DPC2TN90u2uA3lN2lYGDV8901PrqN0x6+Ofb248V1guvh/6nHDmihhTsl4/4sZCg7OW/R8jtoQxeWWAv982gjC++tkRT04wOl3huKrvHgPkCxs56aG03Qtmv9/n2uBPlR4/vUn1pGdbhdb0vyqYPT5vh9tkfgzoW5Zg0/2AYVXGmN+qgaS/oYPfVyXNN6hlHRlVSBqMZwPINSUGPVMqTSJcOv3sY2tVqfEMcOMWAd8Vh+NJKisb2hpS5t8t5XMwE6kkEBAaqXxbBVOOzvwubDq1ewhvD1mLJ8l7ERnpyZhjyQeKcuW6D8nzLlIMXgFa5dVpi3VEqRVziSWqMaLRDzbJtAw7gXuZ190KcR9hao6GEBHfzjYotesXclTTdTe14IGsXQ9ao7duu45qUxcd5+HQdQTIvBdY/Jl3U23lOoH7lhOFnHTw==
  template:
    metadata:
      creationTimestamp: null
      name: transmission-vpn-creds
      namespace: media
