apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tracearr

resources:
  - sealed-secret.yaml
  - 01-db-and-redis.yaml
  - 02-tracearr.yaml

# Pin app version via Kustomize image override
images:
  - name: ghcr.io/connorgallopo/tracearr
    newTag: v2.0.1
